# Generated by Django 6.0.4 on 2026-05-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('passport_image', models.ImageField(upload_to='passports/')),
                ('status', models.CharField(default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
